'use strict';
var parseData = function(arr){
	var temp = '';

	// Add an property on the object called start. 
	for(var j =0;j<arr.length;j++){
		aggregate(arr[j]);
	} 

	
	for(var i =0;i<arr.length;i++){
		temp = arr[i].date;
		arr[i].start.local = temp;
		delete arr[i].date;
	}

	return arr;
};

var aggregate = function(obj){
	obj.start = {};
	return obj;
}

var data = [ { 
    name: { text: 'People in Plazas: Free Smooth Jazz Concert' },
description:{ text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/Jerry_Stucker_Promo_Pic1-150x130.jpg' },
venue: { name: 'Mechanics Monument Plaza' },
city: 'San Francisco',
date: 'Tuesday, September 15 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Jazz Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/citizen12-175x130.jpg' },
venue: { name: 'Rincon Center' },
city: 'San Francisco',
date: 'Tuesday, September 15 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'Mexican Independence Celebration 2015' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/11990560_1136508529711416_1174177894338897753_n-175x130.jpg' },
venue: { name: 'Civic Center Plaza' },
city: 'San Francisco',
date: 'Tuesday, September 15 – 5:15 pm',
cost: 'FREE' },
{ name: { text: 'Win Tix: Rising Eclectic Acoustic Star “Trevor Hall”' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/mFxnTTb1-175x130.jpg' },
venue: { name: 'Slim\'s' },
city: 'Slim’',
date: 'Tuesday, September 15 – 8:00 pm',
cost: 'WIN' },
{ name: { text: 'Win Tix: Live Electronica “SunSquabi”' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/upwxrC71-175x130.jpg' },
venue: { name: 'The Chapel' },
city: 'The Chapel',
date: 'Tuesday, September 15 – 9:00 pm',
cost: 'WIN' },
{ name: { text: 'People in Plazas: Free Delta Blues Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/jakesampsonmattbaxter1-175x130.jpg' },
venue: { name: 'Two Embarcadero Center' },
city: 'San Francisco',
date: 'Wednesday, September 16 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'September Wednesdays Jazz Fest: Coltrane & Celtic Harp' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/Screen-Shot-2015-09-14-at-12.32.57-PM-175x130.png' },
venue: { name: 'Ozumo Oakland' },
city: 'Oakland',
date: 'Wednesday, September 16 – 6:00 pm',
cost: 'FREE' },
{ name: { text: 'Music in the Park: Brazilian Forro Music Concert' },
description: { text: 'Bring a picnic and a blanket, family and friends because it’s Music in the Park time again in Albany’s grassy Memorial Park. The 2015 concert series will be the 12th season of providing free concerts from 6:30-8 pm every Wednesday night in September. Don’t forget ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/S3_SS15_article_dona_francesca-175x130.jpg' },
venue: { name: 'Memorial Park (Albany)' },
city: 'Albany',
date: 'Wednesday, September 16 – 6:30 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Smooth Jazz Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/Jerry_Stucker_Promo_Pic11-150x130.jpg' },
venue: { name: 'Transamerica Redwood Park' },
city: 'San Francisco',
date: 'Thursday, September 17 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Western Swing Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/b-stars11-175x130.jpg' },
venue: { name: '333 Market St.' },
city: 'San Francisco',
date: 'Thursday, September 17 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'Live Music Happy Hour Under the Dome' },
description: { text: 'On Thursdays through September, enjoy live music performances Under the Dome on Level 4 of Westfield SF Centre during the Restaurant Collection Happier Hours. 2015 Schedule Thursday, 9/3 – 4-6 pm Thursday, 9/10 – 4-6 pm Thursday, 9/17 – 4-6 pm Thursday, 9/24 – 4-6 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/Screen-Shot-2015-09-03-at-6.32.27-PM-175x130.png' },
venue: { name: 'Westfield San Francisco Centre' },
city: 'Westfield SF',
date: 'Thursday, September 17 – 4:00 pm',
cost: 'FREE' },
{ name: { text: '“Off The Grid” Twilight Campfire Party' },
description: { text: 'Cozy up with Off the Grid at “Twilight at the Presidio” – a free weekly evening event on the Main Post Lawn from 5-9 pm every Thursday,April 2 – October 29, 2015. Off the Grid street food vendors will serve up dishes tapas-style while you ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/09/1495157_542562532525614_897471763_o1-175x130.jpg' },
venue: { name: 'Main Post Lawn' },
city: 'Presidio',
date: 'Thursday, September 17 – 4:00 pm',
cost: 'FREE' },
{ name: { text: 'Hardly Strictly Tribute Concert Series' },
description: { text: 'On select Thursdays, the Contemporary Jewish Museum exhibition Hardly Strictly Warren Hellman will be activated through live music, featuring bands and acts that have performed over the years during Hardly Strictly Bluegrass (HSB). The concerts are free with museum admission, which is $5 every Thursday ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/06/Screen-Shot-2015-06-17-at-9.15.30-PM-175x130.png' },
venue: { name: 'Contemporary Jewish Museum' },
city: 'Contemporary Jewish Museum',
date: 'Thursday, September 17 – 6:00 pm',
cost: '$5*' },
{ name: { text: 'Third Thursday Piedmont Avenue Stroll' },
description: { text: 'At the Piedmont Avenue Stroll you can expect to see a variety of art mediums, enjoy entertainment, and sample refreshments with many businesses showcasing hand-picked local artists and designers. The monthly event was voted Best Art Walk That’s Not Art Murmur in 2012 by the East ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/11/piedmont-avenue-175x130.jpg' },
venue: { name: 'Piedmont Avenue' },
city: 'Oakland',
date: 'Thursday, September 17 – 6:00 pm',
cost: 'FREE' },
{ name: { text: 'Music & Market Summer Concert: Motown Classics' },
description: { text: 'The 27th Annual Music & Market Series returns to Todos Santos Plaza featuring a “Cream of the Crop” schedule of Bay Area bands, and one of the best Farmer’s Markets anywhere in downtown Concord from 6:30-8 pm from May 21 through September 17, 2015. The Music & ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/06/todos-santos-plaza-music1-175x130.jpg' },
venue: { name: 'Todos Santos Plaza' },
city: 'Concord',
date: 'Thursday, September 17 – 6:30 pm',
cost: 'FREE' },
{ name: { text: 'Win Tix: “Tim Flannery” Live Concert with Giants Coach' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/GGrewK81-175x130.jpg' },
venue: { name: 'Slim\'s' },
city: 'Slim’s',
date: 'Thursday, September 17 – 8:00 pm',
cost: 'WIN' },
{ name: { text: 'Win Tix: Superchunk Frontman “Mac McCaughan”' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/UljAIFo1-175x130.jpg' },
venue: { name: 'Rickshaw Stop' },
city: 'Rickshaw Stop',
date: 'Thursday, September 17 – 8:00 pm',
cost: 'WIN' },
{ name: { text: 'People in Plazas: Free Americana Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/jimBo-Trout1-175x130.jpg' },
venue: { name: '101 California' },
city: 'San Francisco',
date: 'Friday, September 18 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Jazz Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/kurt-ribach1_626x350-resized-6001-175x130.png' },
venue: { name: '201 Spear Street' },
city: 'San Francisco',
date: 'Friday, September 18 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Jump Swing Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/san-francisco-wedding-music-stompy-jones1-175x130.jpg' },
venue: { name: '303 Second Street' },
city: 'San Francisco',
date: 'Friday, September 18 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Brazilian Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/Coelho_Ridnell_sm11-175x130.jpg' },
venue: { name: '425 Market' },
city: 'San Francisco',
date: 'Friday, September 18 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'Country Fair: $1 Horse Wagon Rides' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/06/wagon-ride-20132-175x130.jpg' },
venue: { name: 'Bayview Opera House' },
city: 'Bayview',
date: 'Friday, September 18 – 5:00 pm',
cost: 'FREE' },
{ name: { text: '“Off the Grid” Friday Night Food Truck Party' },
description: { text: 'Over 30 food vendors in a huge circle with a full bar and bands in the middle? Now that’s a party; it’s also California’s largest weekly street food market.  Off the Grid is a weekly outdoor food truck bonanza staged every Friday from 5-10 pm at the historic waterfront campus ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/03/otg-175x130.jpeg' },
venue: { name: 'Fort Mason Center' },
city: 'Fort Mason',
date: 'Friday, September 18 – 5:00 pm',
cost: 'FREE' },
{ name: { text: 'Contemporary Music: sfSound' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/08/25_113206431-175x130.jpg' },
venue: { name: 'Presidio Officers\' Club' },
city: 'The Presidio',
date: 'Friday, September 18 – 6:00 pm',
cost: '*' },
{ name: { text: 'Win Tix: Superstar Jam Band “Moonalice” Concert' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/moonalice900x42011-175x130.jpg' },
venue: { name: 'Terrapin Crossroads' },
city: 'San Rafael',
date: 'Friday, September 18 – 8:00 pm',
cost: 'WIN' },
{ name: { text: 'Win Tix: Nashville’s Rusty Rock “Natural Child”' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/GZkhUF91-175x130.jpg' },
venue: { name: 'Brick & Mortar Music Hall' },
city: 'Brick & Mortar Music Hall',
date: 'Friday, September 18 – 9:00 pm',
cost: 'WIN' },
{ name: { text: '2015 “Tour de Fat” Bike & Beer Festival' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/08/9433810-san-francisco-september-25-mucca-pazza-a-self-described-circus-punk-marching-band-performance-at-to1-175x130.jpg' },
venue: { name: 'Lindley Meadow' },
city: 'Golden Gate Park',
date: 'Saturday, September 19 – All Day',
cost: 'FREE' },
{ name: { text: '2015 “Peace In The Park” Festival' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/08/bandshell1-175x130.jpg' },
venue: { name: 'Spreckels Temple of Music' },
city: 'Golden Gate Park',
date: 'Saturday, September 19 – All Day',
cost: 'FREE' },
{ name: { text: 'Win Tix: Jazz & Comedy with “Orange is the New Black’s” Lea DeLaria' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/s0NnnTC1-175x130.jpg' },
venue: { name: 'The Regency Ballroom' },
city: 'The Regency',
date: 'Saturday, September 19 – 8:00 pm',
cost: 'WIN' },
{ name: { text: 'Win Tix: Psychedelic Surf Rock “Mermen”' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/JndsVUo1-175x130.jpg' },
venue: { name: 'The Chapel' },
city: 'The Chapel',
date: 'Saturday, September 19 – 9:00 pm',
cost: 'WIN' },
{ name: { text: '2015 Korea Day Festival: Art, Performance & Food' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2014/08/asian-art-museum1-175x130.jpg' },
venue: { name: 'Asian Art Museum' },
city: 'Asian Art Museum',
date: 'Sunday, September 20 – 11:00 am',
cost: 'FREE' },
{ name: { text: 'Off the Grid: Presidio Picnic & Food Truck Party' },
description: { text: 'Off the Grid hosts a full season of Picnic at the Presidio from 11 am to 4 pm every Sunday through the fall at the Main Parade Ground Lawn. Expect yummy offerings available for purchase from San Francisco’s favorite eateries and food trucks, Mimosa and Bloody Mary drink kits, ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/09/presidio-picnic-175x130.jpg' },
venue: { name: 'Main Post Lawn' },
city: 'San Francisco',
date: 'Sunday, September 20 – 11:00 am',
cost: 'FREE' },
{ name: { text: '“Eats, Beats & Brews” Block Party: Salsa Dancing, Games & Beer Garden' },
description: { text: 'Downtown Berkeley’s Eats, Beats & Brews block party is back for 2015 – with Salsa Sundays featuring live salsa music, along with a Drake’s Brewing outdoor beer garden, delicious food for sale, outdoor seating and Games of Berkeley game pavilion every third Sunday from 12 noon to 6 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/08/salsa-175x130.jpg' },
venue: { name: 'Shattuck & Center (Berkeley)' },
city: 'Berkeley',
date: 'Sunday, September 20 – All Day',
cost: 'FREE' },
{ name: { text: 'Live Jazz Music: Kurt Ribak' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/06/Kurt_MG_0203_fullres-175x130.jpg' },
venue: { name: 'Jane Warner Memorial Plaza' },
city: undefined,
date: 'Sunday, September 20 – 1:00 pm',
cost: 'FREE' },
{ name: { text: 'Spanish Dancing with El Grupo Sabores de España' },
description: { text: 'The Golden Gate Park Band, under the direction of Michael L. Wirgler, presents the 133rd season in Golden Gate Park’s music concourse. The weekly concerts take place most Sundays at 1 pm and are free and open to the public. All concerts feature music of specific ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2011/04/Golden-Gate-Park-Band1-175x130.jpg' },
venue: { name: 'Spreckels Temple of Music' },
city: 'San Francisco',
date: 'Sunday, September 20 – 1:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Jazz Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/kurt-ribach1_626x350-resized-6001-175x130.png' },
venue: { name: 'Jane Warner Memorial Plaza' },
city: 'San Francisco',
date: 'Sunday, September 20 – 1:00 pm',
cost: 'FREE' },
{ name: { text: 'Summer Outdoor Music Series' },
description: { text: 'Celebrating the summer season and Marin’s love for the outdoors Town Center Corte Madera will host its annual Summer Music Series each Sunday June 7th through September 27th from 2-4 pm with a great lineup of music that will appeal to all ages. The series features ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/06/1509690_10153060973924380_4526753914021363512_n-175x130.jpg' },
venue: { name: 'Town Center Corte Madera' },
city: 'Corte Madera',
date: 'Sunday, September 20 – 2:00 pm',
cost: 'FREE' },
{ name: { text: 'Original Famous Twang Sundays: Live Country Music' },
description: { text: 'Original Famous Twang Sundays is a free, all-ages concert series at Thee Parkside in Potrero Hill. Come by every Sunday; there’s always a fresh traditional or contemporary live act and a surprise special to purchase from the kitchen.' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/06/original-twang-175x130.png' },
venue: { name: 'Thee Parkside' },
city: 'Potrero Hill',
date: 'Sunday, September 20 – 4:00 pm',
cost: 'FREE' },
{ name: { text: '“Return of the Cypher” Hip-Hop & Beatbox Jam' },
description: { text: 'Return of the Cypher (ROTC) is free live Hip-Hop show every Sunday at the Boom Boom Room that features an ever-changing lineup of artists and improvised sessions (know as “cyphers”) where beatboxers, emcees, and musicians collaborate in a spontaneous combustion of soulful skill. Every week, The ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/07/rotc-175x130.jpg' },
venue: { name: 'Boom Boom Room' },
city: 'Boom Boom Room',
date: 'Sunday, September 20 – 9:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free R&B Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/kenya-B11-175x130.jpg' },
venue: { name: 'Rincon Center' },
city: 'San Francisco',
date: 'Tuesday, September 22 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Jazz/Blues Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/Faye_Carol_on_Mic3-6001-175x130.jpg' },
venue: { name: 'Mechanics Monument Plaza' },
city: 'San Francisco',
date: 'Tuesday, September 22 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free R&B Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/larryvann11-175x130.jpg' },
venue: { name: 'Civic Center Plaza' },
city: 'San Francisco',
date: 'Wednesday, September 23 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'Union Square Live Psychedelic Music: Moonalice' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/05/11083636_796708480396922_7712033367294240147_n1-175x130.jpg' },
venue: { name: 'Union Square Park' },
city: 'San Francisco',
date: 'Wednesday, September 23 – 6:00 pm',
cost: 'FREE' },
{ name: { text: 'September Wednesdays Jazz Fest' },
description: { text: 'Every Wednesday of September, Ozumo Oakland is hosting live Jazz in their lounge from 6-9 pm. Entry is free. Ozumo is located at 2251 Broadway in downtown Oakland. It’s all about the music, but they will also be offering all of our signature Japanese delicacies. September 2015 Schedule 9/2 – Phat ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/08/jazz-band-175x130.jpg' },
venue: { name: 'Ozumo Oakland' },
city: 'Oakland',
date: 'Wednesday, September 23 – 6:00 pm',
cost: 'FREE' },
{ name: { text: 'Music in the Park: Soul Concert' },
description: { text: 'Bring a picnic and a blanket, family and friends because it’s Music in the Park time again in Albany’s grassy Memorial Park. The 2015 concert series will be the 12th season of providing free concerts from 6:30-8 pm every Wednesday night in September. Don’t forget ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/Soul-Power-300dpi-175x130.jpg' },
venue: { name: 'Memorial Park (Albany)' },
city: 'Albany',
date: 'Wednesday, September 23 – 6:30 pm',
cost: 'FREE' },
{ name: { text: 'Win Tix: Seoul: Fun, Folk Montreal Dream Pop Trio' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/seoul-175x130.jpg' },
venue: { name: 'Bottom of the Hill' },
city: 'Bottom of the Hill',
date: 'Wednesday, September 23 – 9:00 pm',
cost: 'WIN*' },
{ name: { text: 'People in Plazas: Free Jazz Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/citizen13-175x130.jpg' },
venue: { name: 'Transamerica Redwood Park' },
city: 'San Francisco',
date: 'Thursday, September 24 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'Old Blues, Pop & Jazz Music Show' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/04/KallyPrice1-175x130.jpg' },
venue: { name: 'Yerba Buena Gardens (Esplanade)' },
city: 'Yerba Buena Gardens Festival',
date: 'Thursday, September 24 – 12:30 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Reggae Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/lulali1-175x130.jpg' },
venue: { name: 'Mint Plaza' },
city: 'San Francisco',
date: 'Thursday, September 24 – 12:30 pm',
cost: 'FREE' },
{ name: { text: 'Live Music Happy Hour Under the Dome' },
description: { text: 'On Thursdays through September, enjoy live music performances Under the Dome on Level 4 of Westfield SF Centre during the Restaurant Collection Happier Hours. 2015 Schedule Thursday, 9/3 – 4-6 pm Thursday, 9/10 – 4-6 pm Thursday, 9/17 – 4-6 pm Thursday, 9/24 – 4-6 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/Screen-Shot-2015-09-03-at-6.32.27-PM-175x130.png' },
venue: { name: 'Westfield San Francisco Centre' },
city: 'Westfield SF',
date: 'Thursday, September 24 – 4:00 pm',
cost: 'FREE' },
{ name: { text: '“Off The Grid” Twilight Campfire Party' },
description: { text: 'Cozy up with Off the Grid at “Twilight at the Presidio” – a free weekly evening event on the Main Post Lawn from 5-9 pm every Thursday,April 2 – October 29, 2015. Off the Grid street food vendors will serve up dishes tapas-style while you ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/09/1495157_542562532525614_897471763_o1-175x130.jpg' },
venue: { name: 'Main Post Lawn' },
city: 'Presidio',
date: 'Thursday, September 24 – 4:00 pm',
cost: 'FREE' },
{ name: { text: 'Rhythm & Blues Concert: Vintage Trouble' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/milwaukee-concert-vintage-trouble1-175x130.jpg' },
venue: { name: 'Amoeba Music (SF)' },
city: 'San Francisco',
date: 'Thursday, September 24 – 6:00 pm',
cost: 'FREE' },
{ name: { text: 'Beer Friday: Live Music, Food Trucks & Family Party' },
description: { text: 'Enjoy a family friendly, admission-free evening of live music, rotating food trucks and an award winning selection of sustainable handcrafted beer and root beer. There’s free admission, two live bands, and three food trucks. Kids and well behaved dogs are welcome. One dollar from each ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/02/Devils_Canyon_Brewing_Company_2-1-175x130.jpg' },
venue: { name: 'Devil\'s Canyon Brewing Company' },
city: 'San Carlos',
date: 'Friday, September 25 – All Day',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Swing Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/cosmo-alleycats-1_626x3501-175x130.jpg' },
venue: { name: '560 Mission Street' },
city: 'San Francisco',
date: 'Friday, September 25 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Cuban Salsa Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/sandor1-175x130.jpg' },
venue: { name: '201 Spear Street' },
city: 'San Francisco',
date: 'Friday, September 25 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free New Orleans Blues Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/200x133x3atpier23.jpg.pagespeed.ic_.qsPaNg1vZy1-175x130.jpg' },
venue: { name: '101 California' },
city: 'San Francisco',
date: 'Friday, September 25 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'Friday Night Market at UN Plaza' },
description: { text: 'Held every fourth Friday through October, the Night Market in the iconic UN Plaza is the place to spend your Friday night. Night Market provides live music and entertainment, making the UN Plaza the liveliest spot in the city. The Night Market is a free ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/2015-Night-Market-Web-Thumbnail-175x130.jpg' },
venue: { name: 'UN Plaza' },
city: 'San Francisco',
date: 'Friday, September 25 – 5:00 pm',
cost: 'FREE' },
{ name: { text: '“Off the Grid” Friday Night Food Truck Party' },
description: { text: 'Over 30 food vendors in a huge circle with a full bar and bands in the middle? Now that’s a party; it’s also California’s largest weekly street food market.  Off the Grid is a weekly outdoor food truck bonanza staged every Friday from 5-10 pm at the historic waterfront campus ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/03/otg-175x130.jpeg' },
venue: { name: 'Fort Mason Center' },
city: 'Fort Mason',
date: 'Friday, September 25 – 5:00 pm',
cost: 'FREE' },
{ name: { text: 'Point Richmond Concert: Soji & The Afrobeat Band' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/05/point-richmond-music-175x130.png' },
venue: { name: 'Downtown Point Richmond' },
city: 'East Bay',
date: 'Friday, September 25 – 5:30 pm',
cost: 'FREE' },
{ name: { text: 'Candle Lit Labyrinth Walk & Live Music' },
description: { text: 'Walk the free labyrinth at Grace North Church in Berkeley with 97 candles lighting the path, while listening to music every last Friday of the month. Free, but an RSVP is appreciated, though not required. The Winding Way musicians, an acoustic musical group featuring guitar, violin, cello, mandolin, ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2014/01/labyrinth_3-175x130.jpg' },
venue: { name: 'Grace North Church' },
city: 'Berkeley',
date: 'Friday, September 25 – 6:00 pm',
cost: 'FREE' },
{ name: { text: 'Free Vegetarian Dinner Night' },
description: { text: 'VolxKuche or Free-Cafe SF is a free supper club held on the second Friday and fourth Friday of the month with dinner served starting at 6 pm. The food will be vegan when possible, and always vegetarian. They often host live entertainment, so keep an eye out on ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/12/volxkuche-175x130.jpg' },
venue: { name: 'St. John Episcopal Church' },
city: 'San Francisco',
date: 'Friday, September 25 – 6:00 pm',
cost: 'FREE' },
{ name: { text: 'Feral Fourth Fridays Urban Square Dance & Live Music' },
description: { text: 'Don’t spend yer Friday sittin’ at home, chewin’ tobacco all on yer lonesome. C’mon down to the ole book place; bring yer dancin’ legs. Alley Cat Bookstore and Gallery will be hosting the Feral Fourth Fridays Urban Square Dance from 7-9 pm every 4th Friday night. All dances are ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/01/nat_geo__0706_shall_we_dance-175x130.jpg' },
venue: { name: 'Alley Cat Books' },
city: 'San Francisco',
date: 'Friday, September 25 – 7:00 pm',
cost: '$5*' },
{ name: { text: 'Feral Fourth Fridays Urban Square Dance & Live Music' },
description: { text: 'googletag.cmd.push(function() { googletag.display(\'div-gpt-ad-1370026159345-1\'); });' },
logo: { url: undefined },
venue: { name: 'Alley Cat Books' },
city: 'San Francisco',
date: 'Friday, September 25 – 7:00 pm',
cost: '$5*' },
{ name: { text: 'Live Music: La Mandanga' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/08/2-175x130.jpg' },
venue: { name: 'La Peña Cultural Center' },
city: 'Berkeley',
date: 'Friday, September 25 – 8:00 pm',
cost: '$9' },
{ name: { text: 'The Beatles Choir: Volunteer Singalong' },
description: { text: 'Take a sad song and make it better as The Beatles Choir brings cheer to the residents and staff of Laguna Honda Hospital through music, joy, laughter and the timeless songs of the Fab Four. Laguna Honda Hospital is a long-term, skilled nursing and rehabilitation ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/12/beatles-choir-175x130.jpg' },
venue: { name: 'Laguna Honda Hospital' },
city: 'San Francisco',
date: 'Saturday, September 26 – 9:30 am',
cost: 'FREE' },
{ name: { text: '2015 Bay Area Blues Festival: Saturday' },
description: { text: 'Continuing the merger of two great festivals, the Downtown Martinez Italian Street Painting Festival and San Francisco’s Polk Street Blues Festival, get ready for a big two-day street party in Martinez – the 2015 Bay Area Blues Festival. 2015 Bay Area Blues Festival Sat-Sun, September 26-27, 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/08/polk-blues-175x130.jpg' },
venue: { name: 'Downtown Martinez' },
city: 'East Bay',
date: 'Saturday, September 26 – All Day',
cost: 'FREE' },
{ name: { text: '20th Annual Watershed Environmental Poetry Festival' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/09/WS.LOGO_-175x130.gif' },
venue: { name: 'MLK Jr. Civic Center Park (Berkeley)' },
city: 'Berkeley',
date: 'Saturday, September 26 – All Day',
cost: 'FREE' },
{ name: { text: 'Win Tix: Persian Pop-Classical Concert: NeekOn 2015 Festival' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/Screen-Shot-2015-09-14-at-4.30.50-PM-175x130.png' },
venue: { name: 'de Young Museum' },
city: 'de Young Museum',
date: 'Saturday, September 26 – 11:00 am',
cost: 'WIN*' },
{ name: { text: '2015 OktoberFest: Live Bavarian Music, Dancing, Food & Beer' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/oktoberfest1-175x130.jpg' },
venue: { name: 'Swiss Park' },
city: 'Newark',
date: 'Saturday, September 26 – 12:00 pm',
cost: '$5' },
{ name: { text: '“Sketchboard”: Figure Drawing Art Class & Live Music' },
description: { text: 'Join in at the Red Victorian, an elegant 2000sq ft events space, for figure drawing accompanied by live musicians and wine, bringing the art scene back to the Upper Haight one creative community event at a time. There will be easels provided and some materials for ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/05/600_87886042-175x130.jpeg' },
venue: { name: 'The Red Victorian' },
city: 'The Haight',
date: 'Saturday, September 26 – 2:00 pm',
cost: '$5*' },
{ name: { text: 'Danish Pop Mini Concert: Mew' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/08/music-mew1-175x130.jpg' },
venue: { name: 'Amoeba Music (SF)' },
city: 'San Francisco',
date: 'Saturday, September 26 – 2:00 pm',
cost: 'FREE' },
{ name: { text: '2015 Bay Area Blues Festival: Sunday' },
description: { text: 'Continuing the merger of two great festivals, the Downtown Martinez Italian Street Painting Festival and San Francisco’s Polk Street Blues Festival, get ready for a big two-day street party in Martinez – the 2015 Bay Area Blues Festival. 2015 Bay Area Blues Festival Sat-Sun, September 26-27, 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/08/polk-blues-175x130.jpg' },
venue: { name: 'Downtown Martinez' },
city: 'East Bay',
date: 'Sunday, September 27 – All Day',
cost: 'FREE' },
{ name: { text: 'Sunday Assembly: Communty Sing & Meetup' },
description: { text: 'Sunday Assembly is a non-religious congregation that celebrates life. They’ve got the best parts of a church – community, singing, and acts of service – without any of the religious dogma. They typically meet on the fourth Sunday of the month to sing, think, listen, laugh, ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2014/03/SA_FB_Cover_Wonder_Audience1-175x130.jpg' },
venue: { name: 'Oakland Peace Center' },
city: 'Oakland',
date: 'Sunday, September 27 – 11:00 am',
cost: 'FREE' },
{ name: { text: 'Off the Grid: Presidio Picnic & Food Truck Party' },
description: { text: 'Off the Grid hosts a full season of Picnic at the Presidio from 11 am to 4 pm every Sunday through the fall at the Main Parade Ground Lawn. Expect yummy offerings available for purchase from San Francisco’s favorite eateries and food trucks, Mimosa and Bloody Mary drink kits, ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/09/presidio-picnic-175x130.jpg' },
venue: { name: 'Main Post Lawn' },
city: 'San Francisco',
date: 'Sunday, September 27 – 11:00 am',
cost: 'FREE' },
{ name: { text: 'Live Jazz Music: Faye Carol' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/06/fayeCarol-172x130.jpg' },
venue: { name: 'Jane Warner Memorial Plaza' },
city: 'San Francisco',
date: 'Sunday, September 27 – 1:00 pm',
cost: 'FREE' },
{ name: { text: '“A Prison Oratorio” American Culture Musical' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/04/MarcusShelby1-175x130.jpg' },
venue: { name: 'Yerba Buena Gardens (Esplanade)' },
city: 'Yerba Buena Gardens Festival',
date: 'Sunday, September 27 – 1:00 pm',
cost: 'FREE' },
{ name: { text: 'Jazz at the Park' },
description: { text: 'The Golden Gate Park Band, under the direction of Michael L. Wirgler, presents the 133rd season in Golden Gate Park’s music concourse. The weekly concerts take place most Sundays at 1 pm and are free and open to the public. All concerts feature music of specific ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2011/04/Golden-Gate-Park-Band1-175x130.jpg' },
venue: { name: 'Spreckels Temple of Music' },
city: 'Golden Gate Park Band',
date: 'Sunday, September 27 – 1:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Jazz/Blues Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/Faye_Carol_on_Mic3-60011-175x130.jpg' },
venue: { name: 'Jane Warner Memorial Plaza' },
city: 'San Francisco',
date: 'Sunday, September 27 – 1:00 pm',
cost: 'FREE' },
{ name: { text: 'Summer Outdoor Music Series' },
description: { text: 'Celebrating the summer season and Marin’s love for the outdoors Town Center Corte Madera will host its annual Summer Music Series each Sunday June 7th through September 27th from 2-4 pm with a great lineup of music that will appeal to all ages. The series features ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/06/1509690_10153060973924380_4526753914021363512_n-175x130.jpg' },
venue: { name: 'Town Center Corte Madera' },
city: 'Corte Madera',
date: 'Sunday, September 27 – 2:00 pm',
cost: 'FREE' },
{ name: { text: 'Live Music: Gutter Swan & Steve Egelman' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/gutterswan-175x130.png' },
venue: { name: 'Sweet Inspiration Bakery Cafe' },
city: 'San Francisco',
date: 'Sunday, September 27 – 4:00 pm',
cost: 'FREE' },
{ name: { text: '“Return of the Cypher” Hip-Hop & Beatbox Jam' },
description: { text: 'Return of the Cypher (ROTC) is free live Hip-Hop show every Sunday at the Boom Boom Room that features an ever-changing lineup of artists and improvised sessions (know as “cyphers”) where beatboxers, emcees, and musicians collaborate in a spontaneous combustion of soulful skill. Every week, The ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/07/rotc-175x130.jpg' },
venue: { name: 'Boom Boom Room' },
city: 'Boom Boom Room',
date: 'Sunday, September 27 – 9:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Smooth Jazz Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/Jerry_Stucker_Promo_Pic12-150x130.jpg' },
venue: { name: 'Rincon Center' },
city: 'San Francisco',
date: 'Tuesday, September 29 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Gypsy Jazz Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/lejazzhot12-175x130.jpg' },
venue: { name: 'Mechanics Monument Plaza' },
city: 'San Francisco',
date: 'Tuesday, September 29 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Steel Drum Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/Shabang1-175x130.jpg' },
venue: { name: 'Civic Center Plaza' },
city: 'San Francisco',
date: 'Wednesday, September 30 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Salsa Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/LaTiDo11-175x130.jpg' },
venue: { name: 'Two Embarcadero Center' },
city: 'San Francisco',
date: 'Wednesday, September 30 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'September Wednesdays Jazz Fest' },
description: { text: 'Every Wednesday of September, Ozumo Oakland is hosting live Jazz in their lounge from 6-9 pm. Entry is free. Ozumo is located at 2251 Broadway in downtown Oakland. It’s all about the music, but they will also be offering all of our signature Japanese delicacies. September 2015 Schedule 9/2 – Phat ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/08/jazz-band-175x130.jpg' },
venue: { name: 'Ozumo Oakland' },
city: 'Oakland',
date: 'Wednesday, September 30 – 6:00 pm',
cost: 'FREE' },
{ name: { text: 'Music in the Park: Michael Jackson Tribute Concert' },
description: { text: 'Bring a picnic and a blanket, family and friends because it’s Music in the Park time again in Albany’s grassy Memorial Park. The 2015 concert series will be the 12th season of providing free concerts from 6:30-8 pm every Wednesday night in September. Don’t forget ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/09/11850076_923880994326537_1193154944_n1-175x130.jpg' },
venue: { name: 'Memorial Park (Albany)' },
city: 'Albany',
date: 'Wednesday, September 30 – 6:30 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Americana Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/axlerodV11-175x130.jpg' },
venue: { name: 'Transamerica Redwood Park' },
city: 'San Francisco',
date: 'Thursday, October 1 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'Chadly & Abdelhadi North African Music' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/04/YassirChadly_Bouchaib1-175x130.jpg' },
venue: { name: 'Yerba Buena Gardens (Esplanade)' },
city: 'Yerba Buena Gardens Festival',
date: 'Thursday, October 1 – 12:30 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Jazz Vocals Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/amanda-king1-175x130.jpg' },
venue: { name: 'Mint Plaza' },
city: 'San Francisco',
date: 'Thursday, October 1 – 12:30 pm',
cost: 'FREE' },
{ name: { text: '“Off The Grid” Twilight Campfire Party' },
description: { text: 'Cozy up with Off the Grid at “Twilight at the Presidio” – a free weekly evening event on the Main Post Lawn from 5-9 pm every Thursday,April 2 – October 29, 2015. Off the Grid street food vendors will serve up dishes tapas-style while you ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/09/1495157_542562532525614_897471763_o1-175x130.jpg' },
venue: { name: 'Main Post Lawn' },
city: 'Presidio',
date: 'Thursday, October 1 – 4:00 pm',
cost: 'FREE' },
{ name: { text: '1st & 3rd Thursday “Hub CAP” Community Art Party' },
description: { text: 'Every first and third Thursday evening, The Hub Vallejo hosts Hub CAP Community Art Party, a creative community gathering where anything goes  – painting, singing, sewing, knitting, music, mosaics, sculpture…whatever. It’s informal and a chance to hang as a community and create. Bring a project, a ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2014/10/10710731_10205081047884700_1137142500272104932_n-175x130.jpg' },
venue: { name: 'The Hub Vallejo' },
city: 'Vallejo',
date: 'Thursday, October 1 – 6:00 pm',
cost: 'FREE' },
{ name: { text: 'Hardly Strictly Bluegrass 2015: Friday' },
description: { text: 'October 2-4 marks the 2015 rendition of one of the largest (and free-est) music festivals in the country. Be one of 750,000+ at San Francisco original own Hardly Strictly Bluegrass. Hardly Strictly Bluegrass 2015 Three days, seven stages, over 100 artists Friday-Sunday, October 2-4, 2015 Hellman ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2011/09/bluegrass-oct-31-175x130.jpg' },
venue: { name: 'Hellman Hollow' },
city: 'Golden Gate Park',
date: 'Friday, October 2 – All Day',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Hawaiian Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/steveespaniola11-175x130.jpg' },
venue: { name: 'Crocker Galleria' },
city: 'San Francisco',
date: 'Friday, October 2 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Blues Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/patwilder12-175x130.jpg' },
venue: { name: '201 Spear Street' },
city: 'San Francisco',
date: 'Friday, October 2 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Brazilian Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/Coelho_Ridnell_sm12-175x130.jpg' },
venue: { name: '101 California' },
city: 'San Francisco',
date: 'Friday, October 2 – 12:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Gypsy Jazz Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/bistro-moustache1-154x130.jpg' },
venue: { name: '425 Market' },
city: 'San Francisco',
date: 'Friday, October 2 – 12:00 pm',
cost: 'FREE' },
{ name: { text: '“Off the Grid” Friday Night Food Truck Party' },
description: { text: 'Over 30 food vendors in a huge circle with a full bar and bands in the middle? Now that’s a party; it’s also California’s largest weekly street food market.  Off the Grid is a weekly outdoor food truck bonanza staged every Friday from 5-10 pm at the historic waterfront campus ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/03/otg-175x130.jpeg' },
venue: { name: 'Fort Mason Center' },
city: 'Fort Mason',
date: 'Friday, October 2 – 5:00 pm',
cost: 'FREE' },
{ name: { text: 'South First Fridays Art Walk' },
description: { text: 'Join an eclectic evening of arts and culture in downtown San Jose’s SoFA district (and beyond) every first Friday of the month. Come check out nearly 20 galleries, shops, bars and even a yoga studio  — all venues participating in South First Fridays, a free ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/10/sofa-first-friday-175x130.jpg' },
venue: { name: 'SoFA District (San Jose)' },
city: 'San Jose',
date: 'Friday, October 2 – 7:00 pm',
cost: 'FREE' },
{ name: { text: '“Wrapped in Plastic” Jazz Quartet' },
description: { text: 'Wrapped in Plastic provides fresh sounds of old and new jazz to the Bay Area. In addition to an ever-expanding repertoire of jazz originals, the group reinterprets old favorites and lesser-known gems in new and modern ways – passing from Miles Davis to the music ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/03/wrapped-175x130.jpg' },
venue: { name: 'The Royale' },
city: 'The Royale',
date: 'Friday, October 2 – 9:00 pm',
cost: 'FREE' },
{ name: { text: 'Hardly Strictly Bluegrass 2015: Saturday' },
description: { text: 'October 2-4 marks the 2015 rendition of one of the largest (and free-est) music festivals in the country. Be one of 750,000+ at San Francisco original own Hardly Strictly Bluegrass. Hardly Strictly Bluegrass 2015 Three days, seven stages, over 100 artists Friday-Sunday, October 2-4, 2015 Hellman ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2011/09/bluegrass-oct-31-175x130.jpg' },
venue: { name: 'Hellman Hollow' },
city: 'Golden Gate Park',
date: 'Saturday, October 3 – All Day',
cost: 'FREE' },
{ name: { text: '21st Century Jazz Concert' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/04/YosvanyTerry1-175x130.jpg' },
venue: { name: 'Yerba Buena Gardens (Esplanade)' },
city: 'Yerba Buena Gardens Festival',
date: 'Saturday, October 3 – 1:00 pm',
cost: 'FREE' },
{ name: { text: 'Sea Chantey Sing Along Aboard Historic Ship' },
description: { text: 'Sailors and scallywags alike gather around for an evening of traditional sea songs and chanteys for the San Francisco Maritime National Historical Park’s monthly chantey on the first Saturday night of each month at 8 pm. Park rangers will lead the public in traditional sea-faring tunes ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2011/08/Playing-Guys-175x130.gif' },
venue: { name: 'SF Maritime National Historical Park' },
city: 'San Francisco',
date: 'Saturday, October 3 – 8:00 pm',
cost: 'FREE' },
{ name: { text: 'Push The Feeling DJ Night' },
description: { text: 'Push The Feeling is monthly dance party happening every first Saturday at Underground SF (424 Haight St.) in the Lower Haight. Resident DJs YR Skull and epicsauce invite local and out-of-town guest DJs to their decks every month. The party is typically free before 10 pm with an RSVP, ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/11/push-the-feeling-175x130.png' },
venue: { name: 'Underground SF' },
city: 'Lower Haight',
date: 'Saturday, October 3 – 9:00 pm',
cost: 'FREE' },
{ name: { text: 'Hardly Strictly Bluegrass 2015: Sunday' },
description: { text: 'October 2-4 marks the 2015 rendition of one of the largest (and free-est) music festivals in the country. Be one of 750,000+ at San Francisco original own Hardly Strictly Bluegrass. Hardly Strictly Bluegrass 2015 Three days, seven stages, over 100 artists Friday-Sunday, October 2-4, 2015 Hellman ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/08/Hardly_Strictly_Bluegrass_20101-175x130.jpg' },
venue: { name: 'Hellman Hollow' },
city: 'Golden Gate Park',
date: 'Sunday, October 4 – All Day',
cost: 'FREE' },
{ name: { text: 'Grande Finale: All Request Program' },
description: { text: 'The Golden Gate Park Band, under the direction of Michael L. Wirgler, presents the 133rd season in Golden Gate Park’s music concourse. The weekly concerts take place most Sundays at 1 pm and are free and open to the public. All concerts feature music of specific ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2011/04/Golden-Gate-Park-Band1-175x130.jpg' },
venue: { name: 'Spreckels Temple of Music' },
city: 'Golden Gate Park Band',
date: 'Sunday, October 4 – 1:00 pm',
cost: 'FREE' },
{ name: { text: '“Return of the Cypher” Hip-Hop & Beatbox Jam' },
description: { text: 'Return of the Cypher (ROTC) is free live Hip-Hop show every Sunday at the Boom Boom Room that features an ever-changing lineup of artists and improvised sessions (know as “cyphers”) where beatboxers, emcees, and musicians collaborate in a spontaneous combustion of soulful skill. Every week, The ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/07/rotc-175x130.jpg' },
venue: { name: 'Boom Boom Room' },
city: 'Boom Boom Room',
date: 'Sunday, October 4 – 9:00 pm',
cost: 'FREE' },
{ name: { text: 'Free First Monday Concert' },
description: { text: 'Every first Monday of the month, The Make-Out Room presents a free concert with several local bands showing off the cutting edge of jazz and improvised music. Expect progressive sounds with a mix of anything from jazz, folk, rock to electronic music.' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/11/481143_433285450057196_1264585988_n-175x130.jpg' },
venue: { name: 'Make-Out Room' },
city: 'Make-Out Room',
date: 'Monday, October 5 – 8:00 pm',
cost: 'FREE' },
{ name: { text: 'Beatles Karaoke Night' },
description: { text: 'Do you think your bird can sing? If so, Joshua Raoul Brody (Tango Number 9) will give you and the Fab Four a piano-bar treatment at the Beatles-only karaoke night at The Royale, a neighborhood bar in the Tenderloin.' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2011/06/beatles-1964-175x130.jpg' },
venue: { name: 'The Royale' },
city: 'Trendynob',
date: 'Monday, October 5 – 8:00 pm',
cost: 'FREE' },
{ name: { text: 'Open Mic Night in a Movie Theater' },
description: { text: 'Come on up and share your creative side at the New Parkway Open Mic – the only late night open mic inside a movie theater. All forms of expression are welcome, be it music, poetry, spoken word, comedy, or getting your weeknight kicks. There will ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2014/01/1526386_714991918525167_244336727_n-175x130.jpg' },
venue: { name: 'The New Parkway' },
city: 'The New Parkway',
date: 'Monday, October 5 – 8:45 pm',
cost: 'FREE' },
{ name: { text: 'Wood Shoppe Free Concert Series' },
description: { text: 'Wood Shoppe is a free monthly music series at Brick & Mortar Music Hall taking place every first Tuesday of the month. Get exposed to local and national emerging artists without the pressure of a cover charge. $3 Trumer Pils and $5 Sailor Jerry cocktails ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/10/brick-and-mortar-concert-175x130.jpg' },
venue: { name: 'Brick & Mortar Music Hall' },
city: 'Brick & Mortar',
date: 'Tuesday, October 6 – 8:00 pm',
cost: 'FREE' },
{ name: { text: '“Off The Grid” Twilight Campfire Party' },
description: { text: 'Cozy up with Off the Grid at “Twilight at the Presidio” – a free weekly evening event on the Main Post Lawn from 5-9 pm every Thursday,April 2 – October 29, 2015. Off the Grid street food vendors will serve up dishes tapas-style while you ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/09/1495157_542562532525614_897471763_o1-175x130.jpg' },
venue: { name: 'Main Post Lawn' },
city: 'Presidio',
date: 'Thursday, October 8 – 4:00 pm',
cost: 'FREE' },
{ name: { text: '“Off the Grid” Friday Night Food Truck Party' },
description: { text: 'Over 30 food vendors in a huge circle with a full bar and bands in the middle? Now that’s a party; it’s also California’s largest weekly street food market.  Off the Grid is a weekly outdoor food truck bonanza staged every Friday from 5-10 pm at the historic waterfront campus ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/03/otg-175x130.jpeg' },
venue: { name: 'Fort Mason Center' },
city: 'Fort Mason',
date: 'Friday, October 9 – 5:00 pm',
cost: 'FREE' },
{ name: { text: 'Free Veggie Dinner Night' },
description: { text: 'VolxKuche or Free-Cafe SF is a free supper club held on the second Friday and fourth Friday of the month with dinner served starting at 6 pm. The food will be vegan when possible, and always vegetarian. They often host live entertainment, so keep an eye ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/12/volxkuche-175x130.jpg' },
venue: { name: 'St. John Episcopal Church' },
city: 'San Francisco',
date: 'Friday, October 9 – 6:00 pm',
cost: 'FREE' },
{ name: { text: '“She Rocks” Live Music, Comedy & Drag Showcase' },
description: { text: 'Tired of seeing girls sing sad love songs and acoustic covers of top 40 hits? She Rocks features the most badass female dominant bands the Bay Area has to offer.  See women who rock the stage harder than any stickly strungout dudes in the biz, every ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/01/joan-jett-1-175x130.jpg' },
venue: { name: 'The Fireside Lounge' },
city: 'San Francisco',
date: 'Friday, October 9 – 8:00 pm',
cost: '$5' },
{ name: { text: 'Saturday Children’s Festival in the Park' },
description: { text: 'The iconic Jerry Garcia Amphitheater at McLaren Park features a variety of local performers and varied music genres from August to October 2015. Situated on a sunny hillside meadow and surrounded by tall shade trees, the Jerry Garcia Amphitheatre creates an intimate, friendly setting, allowing ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/08/jerry-garcia-amphitheatre-175x130.jpg' },
venue: { name: 'Jerry Garcia Amphitheatre (McLaren Park)' },
city: 'McLaren Park',
date: 'Saturday, October 10 – 11:00 am',
cost: 'FREE' },
{ name: { text: 'Downtown Campbell Second Saturdays: Music, Art & Food' },
description: { text: 'Downtown Campbell Second Saturdays feature live entertainment, art and artists, shopping, and food from 2-6 pm on the second Saturday of every month. Come down to East Campbell Avenue and Central for an afternoon of live music and entertainment for the whole family.' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/11/campbell-175x130.jpg' },
venue: { name: 'Downtown Campbell' },
city: undefined,
date: 'Saturday, October 10 – 2:00 pm',
cost: 'FREE' },
{ name: { text: 'Shapeshifters Cinema: Experimental Film & Music' },
description: { text: 'Shapeshifters Cinema is a monthly series featuring experimental filmmakers and video artists presenting moving image work live with accompaniment from musicians and sound artists. Shapeshifters takes place the second Sunday of every month, from 8 to 9 pm (unless otherwise noted) at Temescal Art Center ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/07/shapeshifters-175x130.jpg' },
venue: { name: 'Temescal Art Center' },
city: 'Oakland',
date: 'Sunday, October 11 – 8:00 pm',
cost: 'FREE' },
{ name: { text: '“Return of the Cypher” Hip-Hop & Beatbox Jam' },
description: { text: 'Return of the Cypher (ROTC) is free live Hip-Hop show every Sunday at the Boom Boom Room that features an ever-changing lineup of artists and improvised sessions (know as “cyphers”) where beatboxers, emcees, and musicians collaborate in a spontaneous combustion of soulful skill. Every week, The ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/07/rotc-175x130.jpg' },
venue: { name: 'Boom Boom Room' },
city: 'Boom Boom Room',
date: 'Sunday, October 11 – 9:00 pm',
cost: 'FREE' },
{ name: { text: 'Wheel of Karaoke: Comedy & Music Battle' },
description: { text: '“Wheel of Karaoke” is a fun and engaging karaoke game show judged and MC’d by local up-and-coming performers of comedy and music, taking place on every second Monday at the Make-Out Room Guest comedians, musicians, and vaudeville acts cameo throughout the night to make this ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2014/06/KJpaulcostumekaraoke-175x130.jpg' },
venue: { name: 'Make-Out Room' },
city: 'Make-Out Room',
date: 'Monday, October 12 – 9:00 pm',
cost: 'FREE' },
{ name: { text: 'Litquake: Outdoor Poetry & Music' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/04/litquake_201412-175x130.png' },
venue: { name: 'Jessie Square' },
city: 'Yerba Buena Gardens Festival',
date: 'Tuesday, October 13 – 12:30 pm',
cost: 'FREE' },
{ name: { text: 'San Francisco Music Video Mini-Fest' },
description: { text: 'Over 10 local bands will take over Bazaar Cafe to screen their recent music videos and talk about their creative and production process on September 2, 2015 and October 14, 2015. There’s a good mix of big-productions and creative low-budget videos. The September 2 lineup includes the latest Candace ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/08/Screen-Shot-2015-09-01-at-2.13.42-PM-175x130.png' },
venue: { name: 'Bazaar Cafe' },
city: 'Bazaar Cafe',
date: 'Wednesday, October 14 – 7:00 pm',
cost: 'FREE' },
{ name: { text: '“Off The Grid” Twilight Campfire Party' },
description: { text: 'Cozy up with Off the Grid at “Twilight at the Presidio” – a free weekly evening event on the Main Post Lawn from 5-9 pm every Thursday,April 2 – October 29, 2015. Off the Grid street food vendors will serve up dishes tapas-style while you ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/09/1495157_542562532525614_897471763_o1-175x130.jpg' },
venue: { name: 'Main Post Lawn' },
city: 'Presidio',
date: 'Thursday, October 15 – 4:00 pm',
cost: 'FREE' },
{ name: { text: 'Third Thursday Piedmont Avenue Stroll' },
description: { text: 'At the Piedmont Avenue Stroll you can expect to see a variety of art mediums, enjoy entertainment, and sample refreshments with many businesses showcasing hand-picked local artists and designers. The monthly event was voted Best Art Walk That’s Not Art Murmur in 2012 by the East ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/11/piedmont-avenue-175x130.jpg' },
venue: { name: 'Piedmont Avenue' },
city: 'Oakland',
date: 'Thursday, October 15 – 6:00 pm',
cost: 'FREE' },
{ name: { text: '“3rd On Third” Arts & Music' },
description: { text: 'San Francisco’s Bayview Neighborhood comes alive for 3rd on Third, a community-wide arts celebration for the whole family happening from 5-8 pm every third Friday of the month, at Bayview Town Center (3rd Street from McKinnon to Palou & Mendell Plaza). The monthly event will feature ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/06/bayview-mural-175x130.png' },
venue: { name: 'Bayview Opera House' },
city: 'Bayview',
date: 'Friday, October 16 – 5:00 pm',
cost: 'FREE' },
{ name: { text: '“Off the Grid” Friday Night Food Truck Party' },
description: { text: 'Over 30 food vendors in a huge circle with a full bar and bands in the middle? Now that’s a party; it’s also California’s largest weekly street food market.  Off the Grid is a weekly outdoor food truck bonanza staged every Friday from 5-10 pm at the historic waterfront campus ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/03/otg-175x130.jpeg' },
venue: { name: 'Fort Mason Center' },
city: 'Fort Mason',
date: 'Friday, October 16 – 5:00 pm',
cost: 'FREE' },
{ name: { text: 'Saturday Blues Concert in the Park' },
description: { text: 'The iconic Jerry Garcia Amphitheater at McLaren Park features a variety of local performers and varied music genres from August to October 2015. Situated on a sunny hillside meadow and surrounded by tall shade trees, the Jerry Garcia Amphitheatre creates an intimate, friendly setting, allowing ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/08/jerry-garcia-amphitheatre-175x130.jpg' },
venue: { name: 'Jerry Garcia Amphitheatre (McLaren Park)' },
city: 'McLaren Park',
date: 'Saturday, October 17 – 1:00 pm',
cost: 'FREE' },
{ name: { text: 'Inner Sunset Sundays 2015' },
description: { text: 'Inner Sunset Sundays is a cross between a block party, a festival, and a street fair. The whole neighborhood is invited to create a public space where everyone can all enjoy their community, food, music, games, dance, art, children’s activities, after-dark surprises, and more. 2015 Inner ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/09/MVC_9776i1-175x130.jpg' },
venue: { name: 'Inner Sunset' },
city: 'October Block Party & Flea Market',
date: 'Sunday, October 18 – All Day',
cost: 'FREE' },
{ name: { text: '“Eats, Beats & Brews” Block Party: Salsa Dancing, Games & Beer Garden' },
description: { text: 'Downtown Berkeley’s Eats, Beats & Brews block party is back for 2015 – with Salsa Sundays featuring live salsa music, along with a Drake’s Brewing outdoor beer garden, delicious food for sale, outdoor seating and Games of Berkeley game pavilion every third Sunday from 12 noon to 6 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/08/salsa-175x130.jpg' },
venue: { name: 'Shattuck & Center (Berkeley)' },
city: 'Berkeley',
date: 'Sunday, October 18 – All Day',
cost: 'FREE' },
{ name: { text: '“Return of the Cypher” Hip-Hop & Beatbox Jam' },
description: { text: 'Return of the Cypher (ROTC) is free live Hip-Hop show every Sunday at the Boom Boom Room that features an ever-changing lineup of artists and improvised sessions (know as “cyphers”) where beatboxers, emcees, and musicians collaborate in a spontaneous combustion of soulful skill. Every week, The ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/07/rotc-175x130.jpg' },
venue: { name: 'Boom Boom Room' },
city: 'Boom Boom Room',
date: 'Sunday, October 18 – 9:00 pm',
cost: 'FREE' },
{ name: { text: '“Off The Grid” Twilight Campfire Party' },
description: { text: 'Cozy up with Off the Grid at “Twilight at the Presidio” – a free weekly evening event on the Main Post Lawn from 5-9 pm every Thursday,April 2 – October 29, 2015. Off the Grid street food vendors will serve up dishes tapas-style while you ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/09/1495157_542562532525614_897471763_o1-175x130.jpg' },
venue: { name: 'Main Post Lawn' },
city: 'Presidio',
date: 'Thursday, October 22 – 4:00 pm',
cost: 'FREE' },
{ name: { text: 'Friday Night Market at UN Plaza' },
description: { text: 'Held every fourth Friday through October, the Night Market in the iconic UN Plaza is the place to spend your Friday night. Night Market provides live music and entertainment, making the UN Plaza the liveliest spot in the city. The Night Market is a free ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/2015-Night-Market-Web-Thumbnail-175x130.jpg' },
venue: { name: 'UN Plaza' },
city: 'San Francisco',
date: 'Friday, October 23 – 5:00 pm',
cost: 'FREE' },
{ name: { text: '“Off the Grid” Friday Night Food Truck Party' },
description: { text: 'Over 30 food vendors in a huge circle with a full bar and bands in the middle? Now that’s a party; it’s also California’s largest weekly street food market.  Off the Grid is a weekly outdoor food truck bonanza staged every Friday from 5-10 pm at the historic waterfront campus ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/03/otg-175x130.jpeg' },
venue: { name: 'Fort Mason Center' },
city: 'Fort Mason',
date: 'Friday, October 23 – 5:00 pm',
cost: 'FREE' },
{ name: { text: 'Free Vegetarian Dinner Night' },
description: { text: 'VolxKuche or Free-Cafe SF is a free supper club held on the second Friday and fourth Friday of the month with dinner served starting at 6 pm. The food will be vegan when possible, and always vegetarian. They often host live entertainment, so keep an eye out on ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/12/volxkuche-175x130.jpg' },
venue: { name: 'St. John Episcopal Church' },
city: 'San Francisco',
date: 'Friday, October 23 – 6:00 pm',
cost: 'FREE' },
{ name: { text: 'Feral Fourth Fridays Urban Square Dance & Live Music' },
description: { text: 'Don’t spend yer Friday sittin’ at home, chewin’ tobacco all on yer lonesome. C’mon down to the ole book place; bring yer dancin’ legs. Alley Cat Bookstore and Gallery will be hosting the Feral Fourth Fridays Urban Square Dance from 7-9 pm every 4th Friday night. All dances are ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/01/nat_geo__0706_shall_we_dance-175x130.jpg' },
venue: { name: 'Alley Cat Books' },
city: 'San Francisco',
date: 'Friday, October 23 – 7:00 pm',
cost: '$5*' },
{ name: { text: 'Sunday Assembly: Communty Sing & Meetup' },
description: { text: 'Sunday Assembly is a non-religious congregation that celebrates life. They’ve got the best parts of a church – community, singing, and acts of service – without any of the religious dogma. They typically meet on the fourth Sunday of the month to sing, think, listen, laugh, ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2014/03/SA_FB_Cover_Wonder_Audience1-175x130.jpg' },
venue: { name: 'Oakland Peace Center' },
city: 'Oakland',
date: 'Sunday, October 25 – 11:00 am',
cost: 'FREE' },
{ name: { text: 'Mixed Media Mixer: Art, Music, Photo & Video Showcase' },
description: { text: 'The Mixed Media Mixer is a monthly event with the goal of bringing artists across many platforms together with the intention of collaboration. A new collection of Bay Area artists, musicians, photographers and videographers come together every last Sunday of the month at the Firehouse Art Events Hangar. Bring ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/11/arts-hangar-175x130.jpg' },
venue: { name: 'Firehouse Art Collective' },
city: 'Berkeley',
date: 'Sunday, October 25 – 3:00 pm',
cost: 'FREE' },
{ name: { text: 'People in Plazas: Free Afro-Cuban Concert' },
description: { text: 'This free annual outdoor music festival puts on over 140 free lunchtime concerts of all styles from July to October in over 15 different public plazas stretched from the Embarcadero through the Castro. Funcheap is proud to be a media sponsor of the 2015 festival. 2015 ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/07/t-mambo11-175x130.jpg' },
venue: { name: 'One Embarcadero Center' },
city: 'San Francisco',
date: 'Tuesday, October 27 – 12:00 pm',
cost: 'FREE' },
{ name: { text: '2015 “Best of Bernal” Film Night, Reception & Music' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/08/6104937415_f0be6e014b1-175x130.jpg' },
venue: { name: 'Mission Cultural Center for Latino Arts' },
city: 'San Francisco',
date: 'Tuesday, October 27 – 7:00 pm',
cost: 'FREE' },
{ name: { text: '“Off The Grid” Twilight Campfire Party' },
description: { text: 'Cozy up with Off the Grid at “Twilight at the Presidio” – a free weekly evening event on the Main Post Lawn from 5-9 pm every Thursday,April 2 – October 29, 2015. Off the Grid street food vendors will serve up dishes tapas-style while you ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/09/1495157_542562532525614_897471763_o1-175x130.jpg' },
venue: { name: 'Main Post Lawn' },
city: 'Presidio',
date: 'Thursday, October 29 – 4:00 pm',
cost: 'FREE' },
{ name: { text: 'Beer Friday: Live Music, Food Trucks & Family Party' },
description: { text: 'Enjoy a family friendly, admission-free evening of live music, rotating food trucks and an award winning selection of sustainable handcrafted beer and root beer. There’s free admission, two live bands, and three food trucks. Kids and well behaved dogs are welcome. One dollar from each ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/02/Devils_Canyon_Brewing_Company_2-1-175x130.jpg' },
venue: { name: 'Devil\'s Canyon Brewing Company' },
city: 'San Carlos',
date: 'Friday, October 30 – All Day',
cost: 'FREE' },
{ name: { text: '“Off the Grid” Friday Night Food Truck Party' },
description: { text: 'Over 30 food vendors in a huge circle with a full bar and bands in the middle? Now that’s a party; it’s also California’s largest weekly street food market.  Off the Grid is a weekly outdoor food truck bonanza staged every Friday from 5-10 pm at the historic waterfront campus ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/03/otg-175x130.jpeg' },
venue: { name: 'Fort Mason Center' },
city: 'Fort Mason',
date: 'Friday, October 30 – 5:00 pm',
cost: 'FREE' },
{ name: { text: '“Sketchboard”: Figure Drawing Art Class & Live Music' },
description: { text: 'Join in at the Red Victorian, an elegant 2000sq ft events space, for figure drawing accompanied by live musicians and wine, bringing the art scene back to the Upper Haight one creative community event at a time. There will be easels provided and some materials for ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/05/600_87886042-175x130.jpeg' },
venue: { name: 'The Red Victorian' },
city: 'The Haight',
date: 'Saturday, October 31 – 2:00 pm',
cost: '$5*' },
{ name: { text: 'Free First Monday Concert' },
description: { text: 'Every first Monday of the month, The Make-Out Room presents a free concert with several local bands showing off the cutting edge of jazz and improvised music. Expect progressive sounds with a mix of anything from jazz, folk, rock to electronic music.' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/11/481143_433285450057196_1264585988_n-175x130.jpg' },
venue: { name: 'Make-Out Room' },
city: 'Make-Out Room',
date: 'Monday, November 2 – 8:00 pm',
cost: 'FREE' },
{ name: { text: 'Beatles Karaoke Night' },
description: { text: 'Do you think your bird can sing? If so, Joshua Raoul Brody (Tango Number 9) will give you and the Fab Four a piano-bar treatment at the Beatles-only karaoke night at The Royale, a neighborhood bar in the Tenderloin.' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2011/06/beatles-1964-175x130.jpg' },
venue: { name: 'The Royale' },
city: 'Trendynob',
date: 'Monday, November 2 – 8:00 pm',
cost: 'FREE' },
{ name: { text: 'Wood Shoppe Free Concert Series' },
description: { text: 'Wood Shoppe is a free monthly music series at Brick & Mortar Music Hall taking place every first Tuesday of the month. Get exposed to local and national emerging artists without the pressure of a cover charge. $3 Trumer Pils and $5 Sailor Jerry cocktails ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/10/brick-and-mortar-concert-175x130.jpg' },
venue: { name: 'Brick & Mortar Music Hall' },
city: 'Brick & Mortar',
date: 'Tuesday, November 3 – 8:00 pm',
cost: 'FREE' },
{ name: { text: 'South First Fridays Art Walk' },
description: { text: 'Join an eclectic evening of arts and culture in downtown San Jose’s SoFA district (and beyond) every first Friday of the month. Come check out nearly 20 galleries, shops, bars and even a yoga studio  — all venues participating in South First Fridays, a free ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/10/sofa-first-friday-175x130.jpg' },
venue: { name: 'SoFA District (San Jose)' },
city: 'San Jose',
date: 'Friday, November 6 – 7:00 pm',
cost: 'FREE' },
{ name: { text: 'Sea Chantey Sing Along Aboard Historic Ship' },
description: { text: 'Sailors and scallywags alike gather around for an evening of traditional sea songs and chanteys for the San Francisco Maritime National Historical Park’s monthly chantey on the first Saturday night of each month at 8 pm. Park rangers will lead the public in traditional sea-faring tunes ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2011/08/Playing-Guys-175x130.gif' },
venue: { name: 'SF Maritime National Historical Park' },
city: 'San Francisco',
date: 'Saturday, November 7 – 8:00 pm',
cost: 'FREE' },
{ name: { text: 'Push The Feeling DJ Night' },
description: { text: 'Push The Feeling is monthly dance party happening every first Saturday at Underground SF (424 Haight St.) in the Lower Haight. Resident DJs YR Skull and epicsauce invite local and out-of-town guest DJs to their decks every month. The party is typically free before 10 pm with an RSVP, ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/11/push-the-feeling-175x130.png' },
venue: { name: 'Underground SF' },
city: 'Lower Haight',
date: 'Saturday, November 7 – 9:00 pm',
cost: 'FREE' },
{ name: { text: 'Shapeshifters Cinema: Experimental Film & Music' },
description: { text: 'Shapeshifters Cinema is a monthly series featuring experimental filmmakers and video artists presenting moving image work live with accompaniment from musicians and sound artists. Shapeshifters takes place the second Sunday of every month, from 8 to 9 pm (unless otherwise noted) at Temescal Art Center ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/07/shapeshifters-175x130.jpg' },
venue: { name: 'Temescal Art Center' },
city: 'Oakland',
date: 'Sunday, November 8 – 8:00 pm',
cost: 'FREE' },
{ name: { text: 'Wheel of Karaoke: Comedy & Music Battle' },
description: { text: '“Wheel of Karaoke” is a fun and engaging karaoke game show judged and MC’d by local up-and-coming performers of comedy and music, taking place on every second Monday at the Make-Out Room Guest comedians, musicians, and vaudeville acts cameo throughout the night to make this ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2014/06/KJpaulcostumekaraoke-175x130.jpg' },
venue: { name: 'Make-Out Room' },
city: 'Make-Out Room',
date: 'Monday, November 9 – 9:00 pm',
cost: 'FREE' },
{ name: { text: '“She Rocks” Live Music, Comedy & Drag Showcase' },
description: { text: 'Tired of seeing girls sing sad love songs and acoustic covers of top 40 hits? She Rocks features the most badass female dominant bands the Bay Area has to offer.  See women who rock the stage harder than any stickly strungout dudes in the biz, every ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/01/joan-jett-1-175x130.jpg' },
venue: { name: 'The Fireside Lounge' },
city: 'San Francisco',
date: 'Friday, November 13 – 8:00 pm',
cost: '$5' },
{ name: { text: 'Downtown Campbell Second Saturdays: Music, Art & Food' },
description: { text: 'Downtown Campbell Second Saturdays feature live entertainment, art and artists, shopping, and food from 2-6 pm on the second Saturday of every month. Come down to East Campbell Avenue and Central for an afternoon of live music and entertainment for the whole family.' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/11/campbell-175x130.jpg' },
venue: { name: 'Downtown Campbell' },
city: undefined,
date: 'Saturday, November 14 – 2:00 pm',
cost: 'FREE' },
{ name: { text: '“3rd On Third” Arts & Music' },
description: { text: 'San Francisco’s Bayview Neighborhood comes alive for 3rd on Third, a community-wide arts celebration for the whole family happening from 5-8 pm every third Friday of the month, at Bayview Town Center (3rd Street from McKinnon to Palou & Mendell Plaza). The monthly event will feature ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/06/bayview-mural-175x130.png' },
venue: { name: 'Bayview Opera House' },
city: 'Bayview',
date: 'Friday, November 20 – 5:00 pm',
cost: 'FREE' },
{ name: { text: 'Sunday Assembly: Communty Sing & Meetup' },
description: { text: 'Sunday Assembly is a non-religious congregation that celebrates life. They’ve got the best parts of a church – community, singing, and acts of service – without any of the religious dogma. They typically meet on the fourth Sunday of the month to sing, think, listen, laugh, ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2014/03/SA_FB_Cover_Wonder_Audience1-175x130.jpg' },
venue: { name: 'Oakland Peace Center' },
city: 'Oakland',
date: 'Sunday, November 22 – 11:00 am',
cost: 'FREE' },
{ name: { text: 'Free Vegetarian Dinner Night' },
description: { text: 'VolxKuche or Free-Cafe SF is a free supper club held on the second Friday and fourth Friday of the month with dinner served starting at 6 pm. The food will be vegan when possible, and always vegetarian. They often host live entertainment, so keep an eye out on ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/12/volxkuche-175x130.jpg' },
venue: { name: 'St. John Episcopal Church' },
city: 'San Francisco',
date: 'Friday, November 27 – 6:00 pm',
cost: 'FREE' },
{ name: { text: 'Feral Fourth Fridays Urban Square Dance & Live Music' },
description: { text: 'Don’t spend yer Friday sittin’ at home, chewin’ tobacco all on yer lonesome. C’mon down to the ole book place; bring yer dancin’ legs. Alley Cat Bookstore and Gallery will be hosting the Feral Fourth Fridays Urban Square Dance from 7-9 pm every 4th Friday night. All dances are ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2015/01/nat_geo__0706_shall_we_dance-175x130.jpg' },
venue: { name: 'Alley Cat Books' },
city: 'San Francisco',
date: 'Friday, November 27 – 7:00 pm',
cost: '$5*' },
{ name: { text: 'Mixed Media Mixer: Art, Music, Photo & Video Showcase' },
description: { text: 'The Mixed Media Mixer is a monthly event with the goal of bringing artists across many platforms together with the intention of collaboration. A new collection of Bay Area artists, musicians, photographers and videographers come together every last Sunday of the month at the Firehouse Art Events Hangar. Bring ...' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2013/11/arts-hangar-175x130.jpg' },
venue: { name: 'Firehouse Art Collective' },
city: 'Berkeley',
date: 'Sunday, November 29 – 3:00 pm',
cost: 'FREE' },
{ name: { text: 'Free Lunchtime Concert: Holiday Concert 2015' },
description: { text: '' },
logo: { url: 'http://cdn.funcheap.com/wp-content/uploads/2012/06/001_OaklandCityCenter.AlexaMorales-L-175x130.jpg' },
venue: { name: 'Oakland City Center' },
city: 'Oakland',
date: 'Tuesday, December 1 – 12:00 pm',
cost: 'FREE' } ];

var parsed = parseData(data);
console.log(parsed);



